// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SeaCare.Data;

#nullable disable

namespace SeaCare.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240531011614_AlterandoTable")]
    partial class AlterandoTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SeaCare.Models.Artefato", b =>
                {
                    b.Property<int>("ArtefatoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtefatoId"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("descricao_artefato");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nome_artefato");

                    b.HasKey("ArtefatoId");

                    b.ToTable("TBS_Artefato");
                });

            modelBuilder.Entity("SeaCare.Models.Localizacao", b =>
                {
                    b.Property<int>("LocalizacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocalizacaoId"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("cidade_localizacao");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("localidade_localizacao");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("uf_localizacao");

                    b.HasKey("LocalizacaoId");

                    b.ToTable("TBS_Localizacao");
                });

            modelBuilder.Entity("SeaCare.Models.Reporte", b =>
                {
                    b.Property<int>("ReporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReporteId"));

                    b.Property<int>("ArtefatoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("LocalizacaoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("ReporteData")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("ReporteId");

                    b.HasIndex("ArtefatoId");

                    b.HasIndex("LocalizacaoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TBS_Reporte");
                });

            modelBuilder.Entity("SeaCare.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nome_usuario");

                    b.HasKey("UsuarioId");

                    b.ToTable("TBS_Usuario");
                });

            modelBuilder.Entity("SeaCare.Models.Reporte", b =>
                {
                    b.HasOne("SeaCare.Models.Artefato", "Artefato")
                        .WithMany()
                        .HasForeignKey("ArtefatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeaCare.Models.Localizacao", "Localizacao")
                        .WithMany()
                        .HasForeignKey("LocalizacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeaCare.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artefato");

                    b.Navigation("Localizacao");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
